version: '3'

services:
  mysql:
    image: mysql:8.0.27
    platform: linux/x86_64
    environment:
      - MYSQL_USER=sandbox
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=sandbox-nest
      - MYSQL_ROOT_PASSWORD=develop
      - MYSQL_PASSWORD=develop
    ports:
      - "3306:3306"
    networks:
      - mysql-network
  mysql-cli:
    image: mysql:8.0.27
    platform: linux/x86_64
    networks:
      - mysql-network
    command: mysql -hmysql -usandbox -pdevelop sandbox-nest

networks:
  mysql-network:
    driver: bridge
